// ============================================================
// PARCHE ZIPA FEST 2026 — DATOS DE ACTIVIDADES
// Actualiza este archivo para modificar actividades
// ============================================================

const ACTIVIDADES = [
  {
    id: "mural-on",
    num: "01",
    name: "Mural On",
    fullName: "Concurso de Muralismo: Mural On",
    category: "arte",
    categoryLabel: "Arte & Cultura",
    date: "2026-09-18",
    dateDisplay: "18 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "El lienzo más grande de Zipaquirá espera a los artistas urbanos. Mural On es el escenario donde el talento, la identidad y el street art se encuentran para transformar la ciudad. ¿Tienes lo que se necesita?",
    requirements: "Por definir",
    targetAudience: "Jóvenes de 14 a 28 años",
    googleMapsUrl: "",
    status: "open",
    registrationOpen: true,
    specialProcess: "mural-on",
    accentColor: "#60E35F",
    icon: "🎨",
    phases: [
      { id: 1, label: "Convocatoria", active: true },
      { id: 2, label: "Postulaciones", active: false },
      { id: 3, label: "Selección", active: false },
      { id: 4, label: "Finalistas", active: false },
      { id: 5, label: "Votación", active: false },
    ]
  },
  {
    id: "expresarte",
    num: "02",
    name: "ExpresArte",
    fullName: "Exposición de Arte: ExpresArte",
    category: "arte",
    categoryLabel: "Arte & Cultura",
    date: "2026-09-21",
    dateDisplay: "21 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "Una exposición que celebra las múltiples formas de expresión artística juvenil. Pintura, fotografía, escultura, arte digital: todas las voces tienen espacio en ExpresArte.",
    requirements: "Por definir",
    targetAudience: "Jóvenes de 14 a 28 años",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: true,
    specialProcess: null,
    accentColor: "#F91264",
    icon: "🖼️",
  },
  {
    id: "youth-squad-game",
    num: "03",
    name: "Youth Squad Game",
    fullName: "Youth Squad Game",
    category: "gaming",
    categoryLabel: "Gaming",
    date: "2026-09-22",
    dateDisplay: "22 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "Competencia de videojuegos en equipo donde la estrategia, la comunicación y el trabajo en equipo son la clave. Forma tu squad y demuestra que Zipaquirá juega en otro nivel.",
    requirements: "Por definir",
    targetAudience: "Jóvenes de 14 a 28 años",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: true,
    specialProcess: null,
    accentColor: "#4701EF",
    icon: "🎮",
  },
  {
    id: "parche-gamer",
    num: "04",
    name: "Parche Gamer",
    fullName: "Parche Gamer",
    category: "gaming",
    categoryLabel: "Gaming",
    date: "2026-09-22",
    dateDisplay: "22 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "El espacio de los gamers de Zipaquirá. Torneos, comunidad, cultura gamer y mucho más en una jornada diseñada para quienes ven en los videojuegos mucho más que un juego.",
    requirements: "Por definir",
    targetAudience: "Jóvenes de 14 a 28 años",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: true,
    specialProcess: null,
    accentColor: "#04A0F5",
    icon: "🕹️",
  },
  {
    id: "level-up",
    num: "05",
    name: "Level Up 2026",
    fullName: "Premios Juventud: Level Up 2026",
    category: "participacion",
    categoryLabel: "Participación Juvenil",
    date: "2026-09-23",
    dateDisplay: "23 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "Los Premios Juventud que reconocen a quienes están cambiando el juego en Zipaquirá. Categorías que celebran el liderazgo, la innovación, el arte, el deporte y el impacto social.",
    requirements: "Por definir",
    targetAudience: "Jóvenes de 14 a 28 años con impacto en la comunidad",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: true,
    specialProcess: "level-up",
    accentColor: "#F49F22",
    icon: "🏆",
  },
  {
    id: "mural-fit-fest",
    num: "06",
    name: "Mural Fit Fest",
    fullName: "Mural Fit Fest",
    category: "deporte",
    categoryLabel: "Deporte & Bienestar",
    date: "2026-09-24",
    dateDisplay: "24 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "Arte, movimiento y bienestar en un solo espacio. Mural Fit Fest fusiona la energía del deporte con la creatividad del arte urbano para una jornada que activa cuerpo y mente.",
    requirements: "Por definir",
    targetAudience: "Jóvenes de 14 a 28 años",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: true,
    specialProcess: null,
    accentColor: "#FA3308",
    icon: "💪",
  },
  {
    id: "colegios-con-flow",
    num: "07",
    name: "Colegios Con Flow",
    fullName: "Colegios Con Flow",
    category: "arte",
    categoryLabel: "Arte & Cultura",
    date: "2026-09-25",
    dateDisplay: "25 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "Los colegios de Zipaquirá demuestran que tienen flow. Competencia de talentos estudiantiles donde cada institución pone su mejor parche sobre el escenario.",
    requirements: "Por definir",
    targetAudience: "Estudiantes de colegios de Zipaquirá",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: true,
    specialProcess: "colegios-con-flow",
    accentColor: "#F91264",
    icon: "🎵",
  },
  {
    id: "business-lab",
    num: "08",
    name: "Business Lab",
    fullName: "Business Lab: Taller para Emprendedores",
    category: "emprendimiento",
    categoryLabel: "Emprendimiento",
    date: "2026-09-25",
    dateDisplay: "25 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "El laboratorio de ideas donde los jóvenes emprendedores de Zipaquirá aprenden, conectan y construyen. Mentoría, herramientas y comunidad para llevar tu proyecto al siguiente nivel.",
    requirements: "Por definir",
    targetAudience: "Jóvenes emprendedores de 18 a 28 años",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: true,
    specialProcess: null,
    accentColor: "#F49F22",
    icon: "💡",
  },
  {
    id: "parche-bajo-las-estrellas",
    num: "09",
    name: "Parche Bajo Las Estrellas",
    fullName: "Parche Bajo Las Estrellas",
    category: "entretenimiento",
    categoryLabel: "Entretenimiento",
    date: "2026-09-26",
    dateDisplay: "26 SEP",
    time: "Por definir",
    location: "Por definir",
    description: "El cierre perfecto para la Semana de la Juventud. Una noche para celebrar, conectar y vivir Zipaquirá al máximo. Arte, música, comunidad y mucho más bajo el cielo de la ciudad.",
    requirements: "Entrada libre",
    targetAudience: "Toda la comunidad juvenil de Zipaquirá",
    googleMapsUrl: "",
    status: "upcoming",
    registrationOpen: false,
    specialProcess: null,
    accentColor: "#4701EF",
    icon: "🌟",
  },
];

// Categorías para filtros
const CATEGORIAS = [
  { id: "all",           label: "Todas",            color: "#60E35F" },
  { id: "arte",          label: "Arte & Cultura",   color: "#F91264" },
  { id: "gaming",        label: "Gaming",            color: "#4701EF" },
  { id: "emprendimiento",label: "Emprendimiento",    color: "#F49F22" },
  { id: "deporte",       label: "Deporte",           color: "#FA3308" },
  { id: "educacion",     label: "Educación",         color: "#04A0F5" },
  { id: "participacion", label: "Participación",     color: "#FA3308" },
  { id: "entretenimiento",label: "Entretenimiento",  color: "#F91264" },
];

window.ACTIVIDADES = ACTIVIDADES;
window.CATEGORIAS = CATEGORIAS;
